[columns]
league = ['league_id',
                'league_name',
                'league_type',
                'league_logo',
                'country_name',
                'country_code',
                'country_flag',
                'season_year',
                'season_start',
                'season_end',
                'season_current',
                'season_events',
                'season_lineups',
                'season_statistics_fixtures',
                'season_statistics_players',
                'season_standings',
                'season_players',
                'season_top_scorers',
                'season_top_assists',
                'season_top_cards',
                'season_injuries',
                'season_predictions',
                'date_pulled']

players = [
            'league_id',
            'year',
            'player_id',
            'player_name',
            'player_age',
            'player_nationality',
            'player_photo',
            'player_birth_date',
            'player_birth_place',
            'player_birth_country',
            'player_height',
            'player_weight',
            'player_injured',
            'player_team',
            'player_team_name',
            'player_team_logo',
            'player_league',
            'player_league_name',
            'player_league_country',
            'player_league_logo',
            'player_league_flag',
            'player_league_season',
            'player_games_played',
            'player_minutes_played',
            'player_lineups',
            'player_number',
            'player_position',
            'player_rating',
            'player_captain',
            'player_sub_in',
            'player_sub_out',
            'player_sub_on_bench',
            'player_shots_total',
            'player_shots_on',
            'player_goals_total',
            'player_goals_conceded',
            'player_goals_assists',
            'player_saves',
            'player_passes_total',
            'player_passes_key',
            'player_passes_accuracy',
            'player_tackles_total',
            'player_tackles_blocks',
            'player_tackles_interceptions',
            'player_duels_total',
            'player_duels_won',
            'player_dribbles_attempts',
            'player_dribbles_success',
            'player_dribbles_past',
            'player_fouls_committed',
            'player_fouls_drawn',
            'player_cards_yellow',
            'player_cards_yellow_red',
            'player_cards_red',
            'player_penalties_won',
            'player_penalties_commited',
            'player_penalties_scored',
            'player_penalties_missed',
            'player_penalties_saved',
            'date_pulled'
]

teams = ['league_id',
                'year',
                'team_id',
                'team_name',
                'team_logo',
                'team_code',
                'team_country',
                'team_founded',
                'team_national',
                'team_venue_id',
                'team_venue_name',
                'team_venue_address',
                'team_venue_city',
                'team_venue_surface',
                'team_venue_image',
                'date_pulled']